### PR TITLE
Remove dependency on ctr::cipher::zeroize

### PR DESCRIPTION
**Pull request by pronebird**
Use our own `zeroize` instead of the one re-exported from `ctr::cipher::zeroize`

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1771)

### CODE REVIEW

**Review by octol — APPROVED** [review]
Can this maybe lead to possibly multiple versions of zeroize crate being used? And in some corner cases cause issuing resolving mutual dependencies?

**Review by jstuczyn — APPROVED** [review]

**Comment by pronebird** [comment]
@octol I thought that Rust didn't allow multiple versions of the same dependency in a workspace. Same goes for features, that accumulate. Isn't that so?

**Comment by octol** [comment]
> @octol I thought that Rust didn't allow multiple versions of the same dependency in a workspace. Same goes for features, that accumulate. Isn't that so?

As an example we have multiple versions of reqwest in the dependency tree (according to cargo tree)

**Comment by pronebird** [comment]
@octol 

> > @octol I thought that Rust didn't allow multiple versions of the same dependency in a workspace. Same goes for features, that accumulate. Isn't that so?
> 
> As an example we have multiple versions of reqwest in the dependency tree (according to cargo tree)

Yeah that's true. I'd need to learn a bit more to understand the exact behaviour. But conflict shouldn't be a problem in this case since `Zeroizing` is used locally and not passed between crates.

**Pull request merged**
