### PR TITLE
Reorder and add example usage to toplevel uniffi API file

### PR DESCRIPTION
**Pull request by octol**
- Add note at the top of the main uniffi file for usage instructions
- Reorder functions to be roughly in the order they are expected to be called
- Extract out `state_machine` mod

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @octol)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 40 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824#-OEZ2xPz7WA_JfjyaM9v:-OEZ2xPz7WA_JfjyaM9w:b-lxoigx) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/56ed3cf2f0d44916bbd83862bf31686e75780201/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L40)):*
> ```XML
> //!     This will stop the VPN state machine.
> //!
> //! 5. (Optional) shutdown the library: `shutdown()`.
> ```

I think this needs to be done in order for account controller to shutdown gracefully.

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @octol)

**Review by octol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 40 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824#-OEZ2xPz7WA_JfjyaM9v:-OEa7sEu23xsXSOK7yyF:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/56ed3cf2f0d44916bbd83862bf31686e75780201/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L40)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think this needs to be done in order for account controller to shutdown gracefully.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1824#-:-OEoEpO67ObtwprWk2UY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)

**Pull request merged**
