### PR TITLE
Reconnect mixnet on ws connection loss

### PR DESCRIPTION
**Pull request by neacsu**
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 163 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711#-ODCIWDJ8WU5gF82iZ7v:-ODCIWDJ8WU5gF82iZ7w:bjbppnx) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/603ff5b0e95564f1f1ecfe37e6c34af39953a52d/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L163)):*
> ```XML
>     };
> 
>     let mut mixnet_client_config = options.clone().mixnet_client_config.unwrap_or_default();
> ```

Nit: Probably better to clone mixnet_client_config instead of all options.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/bandwidth_controller.rs` line 20 at r2](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711#-ODGmq5vC2qudA7dJniR:-ODGmq5vC2qudA7dJniS:b-fw9dx5) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/f60d2e537c54a032cb4c7c6229bb5c9c5ae9449d/nym-vpn-core/crates/nym-vpn-lib/src/bandwidth_controller.rs#L20)):*
> ```XML
> };
> use nym_wg_gateway_client::{ErrorMessage, GatewayData, WgGatewayClient, WgGatewayLightClient};
> use tokio_util::sync::CancellationToken;
> ```

Nit I started doing use separation using the following pattern:

```rs
use std::...

// external
use tokio::...

// workspace crates
use nym_*::...

// inside of executable/lib
use super::...
```

Not sure if you like it.

**Review by zaneschepke — APPROVED** [review]

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @doums, @octol, @pronebird, and @rokas-ambrazevicius)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/bandwidth_controller.rs` line 20 at r2](https://reviewable.io/reviews/nymtech/nym-vpn-client/1711#-ODGmq5vC2qudA7dJniR:-ODLN6h40G6Sd2gKSypk:b-87wuyq) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/f60d2e537c54a032cb4c7c6229bb5c9c5ae9449d/nym-vpn-core/crates/nym-vpn-lib/src/bandwidth_controller.rs#L20)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit I started doing use separation using the following pattern:

```rs
use std::...

// external
use tokio::...

// workspace crates
use nym_*::...

// inside of executable/lib
use super::...
```

Not sure if you like it.
</blockquote></details>

I like it, I was trying to do something similar, but not very consistently. Applied it here, will try to apply it more in the future as well

**Review by octol — APPROVED** [review]
I say if it works, ship it! :)
Possibly we can take a stab at integrating it further into the state machine later, but I'm not really up to date on what's the best approach there

**Pull request merged**
