### PR TITLE
Add default-members entry in nym-vpn-core workspace

### PR DESCRIPTION
**Pull request by octol**
Add default-members to the `nym-vpn-core` workspace since usually people
only want to build the main binaries, and not bother with e.g
`nym-gateway-probe`.

Adding only `nym-vpnd` and `nym-vpnc`, but transitively most crates will
be built still.

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @octol)

___
*[a discussion](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-ODq8r-b4SyBt5lyD4MM:-ODq8r-b4SyBt5lyD4MN:bjyijgp) (no related file):*
Breaks on iOS: 

```
Run cargo run --bin uniffi-bindgen generate \
  cargo run --bin uniffi-bindgen generate \
    --library target/aarch64-apple-ios/debug/libnym_vpn_lib.a  \
    --config crates/nym-vpn-lib/uniffi.toml \
    --language swift --out-dir build -n
  shell: /bin/bash -e {0}
  env:
    IPHONEOS_DEPLOYMENT_TARGET: 16
    CARGO_TERM_COLOR: always
    AGENT_ISSELFHOSTED: 1
error: no bin target named `uniffi-bindgen`.
Available bin targets:
    nym-vpnc
    nym-vpnd
```

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @octol)

___
*[a discussion](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-ODq8r-b4SyBt5lyD4MM:-OEDuzx1-QoCvO5lVx-j:bja0r7d) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Breaks on iOS: 

```
Run cargo run --bin uniffi-bindgen generate \
  cargo run --bin uniffi-bindgen generate \
    --library target/aarch64-apple-ios/debug/libnym_vpn_lib.a  \
    --config crates/nym-vpn-lib/uniffi.toml \
    --language swift --out-dir build -n
  shell: /bin/bash -e {0}
  env:
    IPHONEOS_DEPLOYMENT_TARGET: 16
    CARGO_TERM_COLOR: always
    AGENT_ISSELFHOSTED: 1
error: no bin target named `uniffi-bindgen`.
Available bin targets:
    nym-vpnc
    nym-vpnd
```
</blockquote></details>

Seems to break on android with uniffi-bindgen too.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)* status: all files reviewed, 2 unresolved discussions (waiting on @octol)

___
*[`nym-vpn-core/Makefile` line 34 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-OEJ8n888CrTm4BXsGlo:-OEJ8n888CrTm4BXsGlp:b-4csjke) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34a4a2715296136a6cf997d5e2a613d02fa7abb1/nym-vpn-core/Makefile#L34)):*
> ```Makefile
> 
> build-win-cross:
> 	cargo build --target x86_64-pc-windows-gnu --release
> ```

Is it missing `--workspace`?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)* status: all files reviewed, 2 unresolved discussions (waiting on @octol)

___
*[`nym-vpn-core/Makefile` line 34 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-OEJ8n888CrTm4BXsGlo:-OEJ8xxsAMjyobPxBLsF:b5xnbmb) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34a4a2715296136a6cf997d5e2a613d02fa7abb1/nym-vpn-core/Makefile#L34)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Is it missing `--workspace`?
</blockquote></details>

@jmwample how do you use this command?

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-:-OEJ_4av3A1RqgNkqPeT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @octol)

**Review by octol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773)* status: all files reviewed, 1 unresolved discussion (waiting on @jmwample)

___
*[`nym-vpn-core/Makefile` line 34 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-OEJ8n888CrTm4BXsGlo:-OEOmWyD7K7u-Yn4EXl4:b-xu6hhz) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34a4a2715296136a6cf997d5e2a613d02fa7abb1/nym-vpn-core/Makefile#L34)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

@jmwample how do you use this command?
</blockquote></details>

I would imagine you don’t want to build e.g gateway probe

**Comment by jmwample** [comment]
> _[`nym-vpn-core/Makefile` line 34 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1773#-OEJ8n888CrTm4BXsGlo:-OEJ8n888CrTm4BXsGlp:b-4csjke) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34a4a2715296136a6cf997d5e2a613d02fa7abb1/nym-vpn-core/Makefile#L34)):_
> 
> > ```makefile
> > build-win-cross:
> > 	cargo build --target x86_64-pc-windows-gnu --release
> > ```
> 
> Is it missing `--workspace`?

> @jmwample how do you use this command?

It is meant to be used however you want. I was using to to build the [default members](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-default-members-field) of the workspace (which this PR adds explicitly). If you want it to build everything you are welcome to add `--workspace`.

in the root `Makefile` I was just using `make windows-cross` to make sure things built properly on windows.

https://github.com/nymtech/nym-vpn-client/blob/9f54c0544b7754ef8c33c0a2da0afef72893bc42/Makefile#L18-L24

p.s. I don't actually have an opinion on this PR, I just wanted to leave a comment for clarity

**Pull request merged**
