### PR TITLE
APPLE: add vpn countries

### PR DESCRIPTION
**Pull request by rokas-ambrazevicius**
Add support for VPN countries. 
Update Status view padding. 
Add country fetching script to prebundle countries.

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @rokas-ambrazevicius and @zaneschepke)

___
*[`nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift` line 240 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211#-O7eAWYiCtIUahJKXsY3:-O7eAWYiCtIUahJKXsY4:b-qul0b7) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/998839b3df49a79307471d7a083aea1943398ede/nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift#L240)):*
> ```Swift
>             let call = client.listCountries(request, callOptions: CallOptions(logger: logger))
>             call.response.whenComplete { result in
>                 switch result {
> ```

Probably can be simplified without a switch statement:

```swift
continuation.resume(with: result.map { res in
  res.countries.map { $0.twoLetterIsoCountryCode } 
})
```
___
*[`nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift` line 249 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211#-O7eB4Ii0eAv6ZM4nY0G:-O7eB4Ii0eAv6ZM4nY0H:b-bj6atq) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/998839b3df49a79307471d7a083aea1943398ede/nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift#L249)):*
> ```Swift
> 
>             call.status.whenComplete { [weak self] result in
>                 switch result {
> ```

Nit: success branch is blank, so this could be matched as:

```swift
if case .failure(error) = result {
  // log error
}
```

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @rokas-ambrazevicius and @zaneschepke)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)* status: all files reviewed, 1 unresolved discussion (waiting on @rokas-ambrazevicius and @zaneschepke)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @rokas-ambrazevicius and @zaneschepke)

**Review by rokas-ambrazevicius — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird and @zaneschepke)

___
*[`nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift` line 240 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1211#-O7eAWYiCtIUahJKXsY3:-O7h47ww-oAnNCncpOnp:b602vsp) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/998839b3df49a79307471d7a083aea1943398ede/nym-vpn-apple/ServicesMacOS/Sources/GRPCManager/GRPCManager.swift#L240)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably can be simplified without a switch statement:

```swift
continuation.resume(with: result.map { res in
  res.countries.map { $0.twoLetterIsoCountryCode } 
})
```
</blockquote></details>

I think we need the error to display in UI if it fails fetching the countries.

**Pull request merged**
