### PR TITLE
Refactor shared mixnet client

### PR DESCRIPTION
**Pull request by neacsu**
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 37 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: 37 of 45 files reviewed, 4 unresolved discussions (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 23 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRD3Yg7F8u_gXOrccX:-ODRD3Yg7F8u_gXOrccY:bgf5mpk) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L23)):*
> ```XML
> }
> 
> impl SharedMixnetClient {
> ```

Nit: oh I'd be happy to get rid of this type as it holds Arc<Mutex<>> and does a lot of unwrapping. Personally I'd for channel instead to keep it safe.
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 26 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRClY-AzcSs_6XshR0:-ODRClY-AzcSs_6XshR1:b-nzi08l) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L26)):*
> ```XML
>     pub fn new(
>         mixnet_client: MixnetClient,
>         #[cfg(target_os = "android")] tun_provider: Arc<dyn AndroidTunProvider>,
> ```

I think it would be much simpler to pass `Fn(RawFd)` instead of `AndroidTunProvider` which should reduce cross-module dependencies.
___
*[`nym-vpn-core/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRCFB16oO16iIs3fow:-ODRCFB16oO16iIs3fox:bbv4eul) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/Cargo.toml#L14)):*
> ```TOML
>     "crates/nym-ip-packet-client",
>     "crates/nym-mixnet-client",
>     "crates/nym-routing", "crates/nym-tunnel-provider",
> ```

nit: add newline between crates
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 48 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRFT1z2Q7XNDObXk9I:-ODRFT1z2Q7XNDObXk9J:b-t2cuci) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L48)):*
> ```XML
> 
> impl ConnectedMixnet {
>     /// Returns the websocket fd owned by mixnet client.
> ```

Please fix documentation

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: 23 of 45 files reviewed, 3 unresolved discussions (waiting on @doums, @octol, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 26 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRClY-AzcSs_6XshR0:-ODfeiNq3vka76sqMvQc:b-ikej4z) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L26)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think it would be much simpler to pass `Fn(RawFd)` instead of `AndroidTunProvider` which should reduce cross-module dependencies.
</blockquote></details>

Did this in the separated PR, thanks for the idea.
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 48 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRFT1z2Q7XNDObXk9I:-ODff0DV9jP8ev69B9Vu:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L48)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please fix documentation
</blockquote></details>

Done.

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: 23 of 45 files reviewed, 3 unresolved discussions (waiting on @doums, @octol, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 23 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODRD3Yg7F8u_gXOrccX:-ODzDUbf-s9jSf4PFFs1:bz38a37) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/34997d0bf726072675f93dea3358aeac70173f08/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L23)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: oh I'd be happy to get rid of this type as it holds Arc<Mutex<>> and does a lot of unwrapping. Personally I'd for channel instead to keep it safe.
</blockquote></details>

Thanks for the input, I'll do this in a separate PR, as on first look, this needs some more changes in the probe, which are out of the scope of this PR.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 45 files at r1, 12 of 19 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: all files reviewed, 6 unresolved discussions (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel_monitor.rs` line 285 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzi4666p8YF0o-ckgN:-ODzi4666p8YF0o-ckgO:b-4vkcmr) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel_monitor.rs#L285)):*
> ```XML
>         #[cfg(target_os = "android")]
>         let bypass_fn = move |_fd: RawFd| {
>             #[cfg(target_os = "android")]
> ```

- This `cfg(target_os = "android")` is not needed  because `bypass_fn` is already guarded by cfg directive.
- `_fd` can be renamed to `fd` since it's always used
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/error.rs` line 2 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzgixv8D6KtoOP14gg:-ODzgixv8D6KtoOP14gh:b5g9tst) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/error.rs#L2)):*
> ```XML
> #[derive(thiserror::Error, Debug)]
> pub enum Error {
> ```

This error looks superficial given that it only has one variant, do we want to use `nym_sdk::Error` directly instead?
___
*[`nym-vpn-core/crates/nym-tunnel-provider/Cargo.toml` line 26 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhYhmBGOK705bmuH_:-ODzhYhmBGOK705bmuHa:b3s7l4l) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-tunnel-provider/Cargo.toml#L26)):*
> ```TOML
> nix = { workspace = true, features = ["socket", "net", "fs"] }
> 
> nym-vpn-account-controller = { path = "../nym-vpn-account-controller" }
> ```

Do we actually need `nym-vpn-account-controller`, `nym-vpn-api-client`, and `nym-gateway-directory` in this crate? These seem to have drifted from `[dependencies]` into `[target.'cfg(unix)'.dependencies]` section.
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 17 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzh6Ru6PDzxy3UdHJp:-ODzh6Ru6PDzxy3UdHJq:b-ex8r75) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L17)):*
> ```XML
>     inner: Arc<tokio::sync::Mutex<Option<MixnetClient>>>,
>     #[cfg(target_os = "android")]
>     bypass_fn: Arc<dyn Fn(RawFd) + Send + Sync>,
> ```

- Does it compile on Android because I don't see `use std::os::fd::RawFd` anywhere?
- Is `Arc<dyn Fn(RawFd) + Send + Sync>` really needed, i.e do we share it? If not we could go for `Box<dyn Fn(RawFd) + Send + Sync>`
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 23 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhE0uEKxvmBHznZts:-ODzhE0uEKxvmBHznZtt:burjjq0) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L23)):*
> ```XML
>     pub fn new(
>         mixnet_client: MixnetClient,
>         #[cfg(target_os = "android")] bypass_fn: Arc<dyn Fn(RawFd) + Send + Sync>,
> ```

Same here, perhaps `RawFd` is not in the scope?
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 72 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhJfT3_IQ9MpGLX5a:-ODzhJfT3_IQ9MpGLX5b:burjjq0) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L72)):*
> ```XML
> 
>     #[cfg(target_os = "android")]
>     pub fn bypass_fn(&self) -> Arc<dyn Fn(RawFd) + Send + Sync> {
> ```

Same here, perhaps `RawFd` is not in the scope?

**Review by pronebird — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: all files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: all files reviewed, 1 unresolved discussion (waiting on @doums, @octol, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 17 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzh6Ru6PDzxy3UdHJp:-ODzjaKN-m2HcyeYvxt_:b-4e2c9x) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

- Does it compile on Android because I don't see `use std::os::fd::RawFd` anywhere?
- Is `Arc<dyn Fn(RawFd) + Send + Sync>` really needed, i.e do we share it? If not we could go for `Box<dyn Fn(RawFd) + Send + Sync>`
</blockquote></details>

`Box` was my initial intent, but it is shared, that's why I switched to `Arc`. I've also fixed the android compilation.
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 23 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhE0uEKxvmBHznZts:-ODzjoy69JdQNsLGOv7I:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L23)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here, perhaps `RawFd` is not in the scope?
</blockquote></details>

Done.
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 72 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhJfT3_IQ9MpGLX5a:-ODzjpbV-Q1Gl0COs1PW:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L72)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here, perhaps `RawFd` is not in the scope?
</blockquote></details>

Done.
___
*[`nym-vpn-core/crates/nym-tunnel-provider/Cargo.toml` line 26 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzhYhmBGOK705bmuH_:-ODzkM9g8326mDXAYbDJ:b-8h2v3r) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-tunnel-provider/Cargo.toml#L26)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Do we actually need `nym-vpn-account-controller`, `nym-vpn-api-client`, and `nym-gateway-directory` in this crate? These seem to have drifted from `[dependencies]` into `[target.'cfg(unix)'.dependencies]` section.
</blockquote></details>

Yes, they're used in `error.rs`.  But good catch, they shouldn't be under unix cfg.
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel_monitor.rs` line 285 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzi4666p8YF0o-ckgN:-ODzkgbT6t-0pNPBRTsR:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel_monitor.rs#L285)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

- This `cfg(target_os = "android")` is not needed  because `bypass_fn` is already guarded by cfg directive.
- `_fd` can be renamed to `fd` since it's always used
</blockquote></details>

Done.
___
*[`nym-vpn-core/crates/nym-mixnet-client/src/error.rs` line 2 at r3](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-ODzgixv8D6KtoOP14gg:-ODzjXob3v6KNQWAv8Ul:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/098823a2e242580a546d319b3a43a7c40599127b/nym-vpn-core/crates/nym-mixnet-client/src/error.rs#L2)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This error looks superficial given that it only has one variant, do we want to use `nym_sdk::Error` directly instead?
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @doums, @octol, @rokas-ambrazevicius, and @zaneschepke)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: all files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[a discussion](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-OE-mFNQ3KKXoHtMtc_W:-OE-mFNQ3KKXoHtMtc_X:b-ok3bxu) (no related file):*
Given that you mentioned issues with uniffi. Please make sure it stays within the vpnlib for now.

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731)* status: 17 of 45 files reviewed, 1 unresolved discussion (waiting on @doums, @octol, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[a discussion](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-OE-mFNQ3KKXoHtMtc_W:-OE-tomE3-9IyDS6BZdU:b-896fix) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Given that you mentioned issues with uniffi. Please make sure it stays within the vpnlib for now.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-:-OEDwZmt-6MkyDaKSmDW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @doums, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-mixnet-client/src/lib.rs` line 5 at r5](https://reviewable.io/reviews/nymtech/nym-vpn-client/1731#-OEDw3zC72J6ICy_lur6:-OEDw3zC72J6ICy_lur7:b4v2syc) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/bbe321f553c1f2a4305675dd09e5be19f28bfe01/nym-vpn-core/crates/nym-mixnet-client/src/lib.rs#L5)):*
> ```XML
> 
> #[cfg(target_os = "android")]
> use std::os::fd::RawFd;
> ```

FYI much nicer this way. Keeps all imports below shorter without FQN

**Pull request merged**
