### PR TITLE
ci: split core

### PR DESCRIPTION
**Pull request by pronebird**
Extract Mac, iOS, Linux, Android workflows from core CI workflow into individual ones.

## New workflows

- ci-nym-vpn-core-android
- ci-nym-vpn-core-linux
- ci-nym-vpn-core-ios
- ci-nym-vpn-core-macos

## Removed

- ci-nym-vpn-core

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1419)

### CODE REVIEW

**Review by octol — APPROVED** [review]
> This PR leaves android and ubuntu in the same bed, I can split them up to if you like this work.

I like this work :)

**Comment by octol** [comment]
Seeing CI being tidied up always brings me joy :)

**Review by pronebird — COMMENTED** [review]
I share the feeling. We deserved that.

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1419#-:-OAMz6gTCdGkr-L4Rd1g:b93uc4t)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @octol and @zaneschepke)

___
*[`.github/workflows/ci-nym-vpn-core-linux.yml` line 36 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1419#gh-1820596066:-OAMzBnf-POrl7wEEQ37:b-uvugp8) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7b810520116269fcbee2adc75d1b6a39aed5417f/.github/workflows/ci-nym-vpn-core-linux.yml#L36)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

I strongly _suspect_ that we don't need triplet anymore, on any of the ci core workflows
</blockquote></details>

About to remove it.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1419)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @octol and @zaneschepke)

___
*[`.github/workflows/ci-nym-vpn-core-linux.yml` line 36 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1419#gh-1820596066:-OAN1-PxEP-3vfXqtshq:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7b810520116269fcbee2adc75d1b6a39aed5417f/.github/workflows/ci-nym-vpn-core-linux.yml#L36)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

About to remove it.
</blockquote></details>

Done.

**Review by octol — APPROVED** [review]

**Comment by pronebird** [comment]
@zaneschepke please have a look, provide your feedback.

**Pull request merged**
