### PR TITLE
Swap from `wireguard-go` to `amneziawg-go`

### PR DESCRIPTION
**Pull request by jmwample**
Swap to using `amneziawg-go` only, with configurable interface in both `nym-wg-go` and in `nym-gateway-probe` (because it bypasses `nym-wg-go`).

This has <ins>**NO**</ins>  changes to functionality as the amnezia features are **disabled by default** (requiring a feature flag to enable them in `nym-wg-go` or `nym-vpn-lib`) and the amnezia go library itself is a fork of `wireguard-go` with minimal changes.

Adding this in to develop would make my life easier as then a "fork" with amnezia enabled only requires changing feature flags and the amnezia configuration we want to use rather than rebase-ing all of these changes each time. (specifically for changes in the gateway probe)

- - -

In order to enable Amnezia you need to BOTH

enable the rust build flag
```toml
nym-wg-go = { workspace=true, features=["amnezia"]}
```

AND provide a configuration (i.e. in `nym-vpn-lib`)
```rs
let wg_exit_config = WgNodeConfig::with_gateway_data( ... )
    .with_amnezia_config(AmneziaConfig::BASE);
```

This means that we can incrementally make steps towards making amnezia available in clients
- Swap `wireguard-go` to `amneziawg-go` (this PR)
- Compile in Amnezia using feature flags in the platform app (i.e. `nym-vpn-lib = { workspace=true, features=["amnezia"]}` in the `nym-vpnd` binary for example), while still using only wireguard features
- Establish a wireguard connection with amnezia features enabled using a configuration provided at runtime

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @jmwample and @octol)

___
*[`nym-vpn-core/README.md` line 33 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817#-OEUtGFVEZDYtdCwo0-1:-OEUtGFVEZDYtdCwo0-2:bhsb7jj) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/612be8a8c3f4502ec0350c01c403fef7775c7633/nym-vpn-core/README.md#L33)):*
> ```Markdown
> ```
> 
> You may need to adjust your `RUSTFLAGS` or `.cargo/config.toml` to ensure that
> ```

Do you happen to know under which circumstances it does not link properly? `nym-wg-go/build.rs` exists specifically to avoid others messing with linker flags, if we know that it doesn't work in some cases, then we should fix it.

**Review by pronebird — COMMENTED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817)* status: all files reviewed, 1 unresolved discussion (waiting on @jmwample and @octol)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817#-:-OEUxdvL1KFi8oWWIiHI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)

**Review by jmwample — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)

___
*[`nym-vpn-core/README.md` line 33 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1817#-OEUtGFVEZDYtdCwo0-1:-OEUxLrWC2LN8KwAa-Xu:b-s4tgwu) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/612be8a8c3f4502ec0350c01c403fef7775c7633/nym-vpn-core/README.md#L33)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Do you happen to know under which circumstances it does not link properly? `nym-wg-go/build.rs` exists specifically to avoid others messing with linker flags, if we know that it doesn't work in some cases, then we should fix it.
</blockquote></details>

I originally wrote this README when you had to mess with these things to get the ffi linking to happen properly (mostly as notes for myself) and then it just stayed. I will update this file to remove that part.

**Pull request merged**
