### PR TITLE
Confine storage interation to the account controller

### PR DESCRIPTION
**Pull request by octol**
Confine storage interaction to the account controller.
This should fix a plethora of account and credential related issues plaguing the vpn client. 

NOTE: breaks compatibility for the uniffi API

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805)

### CODE REVIEW

**Review by rokas-ambrazevicius — APPROVED** [review]

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805)* status: all files reviewed, 3 unresolved discussions (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-proto/src/conversions/into_proto/account.rs` line 4 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESzzSnEbiuWtIIqoXO:-OESzzSnEbiuWtIIqoXP:b-fpgudu) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/59dee703743293cba2eaab63d880ba973be42fb4/nym-vpn-core/crates/nym-vpn-proto/src/conversions/into_proto/account.rs#L4)):*
> ```XML
> // SPDX-License-Identifier: GPL-3.0-only
> 
> impl From<Option<String>> for crate::AccountIdentity {
> ```

That doesn't look right. How come `AccountIdentity` holds `Option<String>`? What does it even mean then? Sounds like what you want is `Option<AccountIdentity>`
___
*[`nym-vpn-core/crates/nym-vpn-account-controller/src/controller.rs` line 272 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESyKsbDTZJlOMnoS4W:-OESyKsbDTZJlOMnoS4X:b-sepnfz) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/59dee703743293cba2eaab63d880ba973be42fb4/nym-vpn-core/crates/nym-vpn-account-controller/src/controller.rs#L272)):*
> ```XML
> 
>     async fn handle_forget_account(&mut self) -> Result<(), AccountCommandError> {
>         tracing::warn!("REMOVING ACCOUNT AND ALL ASSOCIATED DATA");
> ```

nit: maybe info! level instead of warn as it's not really a problem.
___
*[`nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs` line 26 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESzF1n-5S-Y6mjDZ0T:-OESzF1n-5S-Y6mjDZ0U:b382xz8) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/bf64f818aa7cf5c131ff5d172d5dffba3be762bd/nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs#L26)):*
> ```XML
>         };
> 
>         if OsStr::new("credentials_database.db") == file.file_name()
> ```

Do we not store other databases in the same data dir? I am just concerned that forgetting account might inadvertently nuke some other db.

**Comment by octol** [comment]
*[`nym-vpn-core/crates/nym-vpn-proto/src/conversions/into_proto/account.rs` line 4 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESzzSnEbiuWtIIqoXO:-OETPzbL70yhhVTyfNiF:b-ufcsq7) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/37daeadfb80fa26eb0f2656a15d52cc457f7cb62/nym-vpn-core/crates/nym-vpn-proto/src/conversions/into_proto/account.rs#L4)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That doesn't look right. How come `AccountIdentity` holds `Option<String>`? What does it even mean then? Sounds like what you want is `Option<AccountIdentity>`
</blockquote></details>

This is from the proto definition

```proto
message AccountIdentity {
  optional string account_identity = 1;
}

message GetAccountIdentityRequest {}

message GetAccountIdentityResponse {
  oneof id {
    AccountIdentity account_identity = 1;
    AccountError error = 2;
  }
}
```
What what would you suggest in this context?

**Comment by octol** [comment]
*[`nym-vpn-core/crates/nym-vpn-account-controller/src/controller.rs` line 272 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESyKsbDTZJlOMnoS4W:-OETQ_NjAZ0nEr8UnpgP:bdcv6kv) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/37daeadfb80fa26eb0f2656a15d52cc457f7cb62/nym-vpn-core/crates/nym-vpn-account-controller/src/controller.rs#L272)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

nit: maybe info! level instead of warn as it's not really a problem.
</blockquote></details>

Good point!

**Comment by octol** [comment]
*[`nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs` line 26 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESzF1n-5S-Y6mjDZ0T:-OETOe9I9Gh4b2vCx9ow:b-uobpnf) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/2b2c748439bbd3d24e37ed2e0c6f7367efd1e336/nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs#L26)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Do we not store other databases in the same data dir? I am just concerned that forgetting account might inadvertently nuke some other db.
</blockquote></details>

Yes I am uneasy about the whole function. It's about striking a balance about making sure there are no holes, but also not deleting stuff we didn't intend to delete

Let me change it to a list of explicit files

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805)* status: 21 of 27 files reviewed, 2 unresolved discussions (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs` line 26 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-OESzF1n-5S-Y6mjDZ0T:-OEUC-apAZoFlVSo9P3z:b-s9dowx) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/2b2c748439bbd3d24e37ed2e0c6f7367efd1e336/nym-vpn-core/crates/nym-vpn-account-controller/src/util.rs#L26)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

Yes I am uneasy about the whole function. It's about striking a balance about making sure there are no holes, but also not deleting stuff we didn't intend to delete

Let me change it to a list of explicit files
</blockquote></details>

Alternative solution would be to provide a function from each respective module to clean up files that they create. Otherwise it's better than wiping everything :+1:

**Review by pronebird — COMMENTED** [review]
> Reviewed 6 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @doums, @neacsu, @rokas-ambrazevicius, and @zaneschepke)

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1805#-:-OEUDsyY1YxTmMfPV_0y:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @doums, @neacsu, @rokas-ambrazevicius, and @zaneschepke)

**Pull request merged**
