### PR TITLE
Enable poisson process by default

### PR DESCRIPTION
**Pull request by octol**
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-cli/src/main.rs` line 200 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333#-O9Ufic-BR96TpWyh-1D:-O9Ufic-BR96TpWyh-1E:b85olmq) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7aed2cd6ddf58adb694023728df7ee9d440f5156/nym-vpn-core/crates/nym-vpn-cli/src/main.rs#L200)):*
> ```XML
> 
>     let mixnet_client_config = MixnetClientConfig {
>         disable_poisson_rate: args.wireguard_mode || args.disable_poisson_rate,
> ```

You might want to modify sanity checks in https://github.com/nymtech/nym-vpn-client/blob/50dfb789d5d4c1f669a062e9aa17cd02e4232d0c/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L110-L117

Also note `unwrap_or_default()` meaning that by default I call `MixnetClientConfig::default()` which initializes all fields with false including `enable_poisson_rate` but since you flipped the field name I assume you know that.

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/mobile/runner.rs` line 81 at r2](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333#-O9Uh45XDtOAccwKBwBW:-O9Uh45XDtOAccwKBwBX:b-4l1t7z) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/29d999a4a52801b632d0f13b298be820a49c43f8/nym-vpn-core/crates/nym-vpn-lib/src/mobile/runner.rs#L81)):*
> ```XML
>         tracing::info!("User agent: {user_agent}");
> 
>         let generic_config = GenericNymVpnConfig {
> ```

FYI don't worry about that. It's going away.. `GenericNymVpnConfig` does not even exist any longer. :)
___
*[`nym-vpn-core/crates/nym-vpnc/src/cli.rs` line 69 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333#-O9Ugr8C-PCJZDWRHYTW:-O9Ugr8C-PCJZDWRHYTX:br0bfit) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7aed2cd6ddf58adb694023728df7ee9d440f5156/nym-vpn-core/crates/nym-vpnc/src/cli.rs#L69)):*
> ```XML
> 
>     /// Enable Poisson process rate limiting of outbound traffic.
>     #[arg(long, hide = true)]
> ```

FYI sneaky... :)

**Review by pronebird — COMMENTED** [review]
> Reviewed 5 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

**Review by octol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @doums, @neacsu, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-cli/src/main.rs` line 200 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333#-O9Ufic-BR96TpWyh-1D:-O9UhNxF0xQiJ61g20-s:by8z2re) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7aed2cd6ddf58adb694023728df7ee9d440f5156/nym-vpn-core/crates/nym-vpn-cli/src/main.rs#L200)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You might want to modify sanity checks in https://github.com/nymtech/nym-vpn-client/blob/50dfb789d5d4c1f669a062e9aa17cd02e4232d0c/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L110-L117

Also note `unwrap_or_default()` meaning that by default I call `MixnetClientConfig::default()` which initializes all fields with false including `enable_poisson_rate` but since you flipped the field name I assume you know that.
</blockquote></details>

Ah, thanks, I'll update that part

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: all files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @rokas-ambrazevicius, and @zaneschepke)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1333)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @doums, @neacsu, @rokas-ambrazevicius, and @zaneschepke)

**Pull request merged**
