### PR TITLE
Update to latest monorepo

### PR DESCRIPTION
**Pull request by neacsu**
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1379)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1379#-:-O9yWknYD9-xH6w5Qq45:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @doums, @octol, @rokas-ambrazevicius, and @zaneschepke)

**Comment by pronebird** [comment]
Tests fail though

**Comment by octol** [comment]
Is that commit hash from the aero branch?

**Comment by neacsu** [comment]
> Tests fail though

It will get through when magura hits mainnet

> Is that commit hash from the aero branch?

No, it's from magura branch. There were some last minute changes in the api so it was pushed as part of the next release

**Pull request merged**
