### PR TITLE
android: library updates

### PR DESCRIPTION
**Pull request by zaneschepke**
* remove unused code
* add support for env api and switching
* fix language switching bug
* remove passing urls to start and gateways lib api
* map new errors
* move required lib setup to init

This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)

### CODE REVIEW

**Review by octol — CHANGES_REQUESTED** [review]
> Reviewed 1 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)* status: 1 of 55 files reviewed, 6 unresolved discussions (waiting on @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 103 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57cqJ6GWLPWnpZc_1:-OB57cqJ6GWLPWnpZc_2:b7f39dy) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L103)):*
> ```XML
> #[allow(non_snake_case)]
> #[uniffi::export]
> pub fn init(data_dir: String) -> Result<(), VpnError> {
> ```

Nice, yep it's good we move in this direction with a common `init()` call

Do you have the same issue on Android as on iOS where you need to call this not from the UI process but from the tunnel process?
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 111 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56OXzAmwv68-feW5w:-OB56OXzAmwv68-feW5x:brzyyxq) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/daa141fd3d48ae0c2d386e99886c995957878a13/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L111)):*
> ```XML
> #[allow(non_snake_case)]
> #[uniffi::export]
> pub fn stopAccountController() -> Result<(), VpnError> {
> ```

Does this mean it's not possible to stop the account controller anymore? Is it needed?
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 196 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56h8H78HhMyPAyY-Y:-OB56h8H78HhMyPAyY-Z:b-kdjg6h) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L196)):*
> ```XML
> async fn get_gateway_countries(
>     api_url: Url,
>     nym_vpn_api_url: Option<Url>,
> ```

IMHO let's remove the Option<>, here and the other calls. You always need both.
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 298 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56vfn-fIaJwo5QXLD:-OB56vfn-fIaJwo5QXLE:bjkap9f) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L298)):*
> ```XML
> }
> 
> fn get_api_url() -> Url {
> ```

Imho for these urls, we should do then in one call. It's important that they are either both from env variables, or both default. But never mixed.

If you have the full set of env variables exported to the environement, you can also get them in all in once call with `NymNetworkDetails::new_from_env()`. That will then contain everything you need.
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 306 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57Sdr270W-uPTos2k:-OB57Sdr270W-uPTos2l:b1r0wjt) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L306)):*
> ```XML
> }
> 
> fn get_nym_api_url() -> Option<Url> {
> ```

Imho let's return `-> Url` here
___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 308 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57KdG64HjPKW7zdnA:-OB57KdG64HjPKW7zdnB:b-gecfc1) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L308)):*
> ```XML
> fn get_nym_api_url() -> Option<Url> {
>     let default_config = GatewayDirectoryConfig::default();
>     match env::var("NYM_VPN_API") {
> ```

Does it also work on iOS get these from env variables?

**Comment by zaneschepke** [comment]
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 196 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56h8H78HhMyPAyY-Y:-OB5sYfl9NDtOQ3KVyoS:bbf9dfi) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L196)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

IMHO let's remove the Option<>, here and the other calls. You always need both.
</blockquote></details>

Well, how would we handle this because all the way down the line from where we are getting this url it is optional. Should it be changed in all of those places too? This would also involve changes to the nym monorepo so perhaps we should leave for now.

**Comment by zaneschepke** [comment]
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 306 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57Sdr270W-uPTos2k:-OB5uO7P6rJA-5_M_bJw:b5w75dj) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L306)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

Imho let's return `-> Url` here
</blockquote></details>

This is optional throughout the entire codebase so it would be a lot of changes

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)* status: 1 of 55 files reviewed, 6 unresolved discussions (waiting on @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 308 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57KdG64HjPKW7zdnA:-OB6Ey-_CU5BOEN9lhh4:b-dhejk5) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L308)):*
<details><summary><i>Previously, zaneschepke (Zane Schepke) wrote…</i></summary><blockquote>

This is a Rokas question, but I would assume so.
</blockquote></details>

Would it be sufficient enough to use `GatewayDirectoryConfig::new_from_env()` given that we set env anyway? `GatewayDirectoryConfig::default()` returns the mainnet configuration

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)* status: 1 of 55 files reviewed, 7 unresolved discussions (waiting on @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 114 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB6GPBX28NY6EJ9X1W7:-OB6GPBYD8DqwoaoB8lh:b-drqj3l) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L114)):*
> ```XML
> }
> 
> pub fn init_logger() {
> ```

Please keep `initLogger()` exported as we call it form main process on iOS to capture part of logs.

**Comment by zaneschepke** [comment]
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 308 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB57KdG64HjPKW7zdnA:-OB6LZ8l4fx8cqb1eeH7:b2hp7a3) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L308)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Would it be sufficient enough to use `GatewayDirectoryConfig::new_from_env()` given that we set env anyway? `GatewayDirectoryConfig::default()` returns the mainnet configuration
</blockquote></details>

Maybe @octol  has some input on `GatewayDirectoryConfig::new_from_env()` but it looks like it could have the sync issue where we could have one url from env and one url from default mainnet config

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)* status: 1 of 55 files reviewed, 7 unresolved discussions (waiting on @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 111 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56OXzAmwv68-feW5w:-OB6OF2T8ZXZ3EOO5l4-:b-w82dl2) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/daa141fd3d48ae0c2d386e99886c995957878a13/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L111)):*
<details><summary><i>Previously, zaneschepke (Zane Schepke) wrote…</i></summary><blockquote>

Right, we would not be able to stop it. Does the app need to stop it or would it just shut down when we close the app?
</blockquote></details>

On iOS the process is being killed, so we need a way to stop it gracefully before telling the system to exit the tunnel process. I am not sure how that works on Android to be fair.

**Review by zaneschepke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493)* status: 1 of 55 files reviewed, 2 unresolved discussions (waiting on @octol, @pronebird, and @rokas-ambrazevicius)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 298 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB56vfn-fIaJwo5QXLD:-OB5tmXA0qVtC5hZxABh:b2x3eu2) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L298)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

Imho for these urls, we should do then in one call. It's important that they are either both from env variables, or both default. But never mixed.

If you have the full set of env variables exported to the environement, you can also get them in all in once call with `NymNetworkDetails::new_from_env()`. That will then contain everything you need.
</blockquote></details>

All of these urls are optional

**Comment by zaneschepke** [comment]
*[`nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs` line 114 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-OB6GPBX28NY6EJ9X1W7:-OBAoCTP8kudoY5GsLd9:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/ff376dd5cd06e17f69571bd81267f51813a1955e/nym-vpn-core/crates/nym-vpn-lib/src/platform/mod.rs#L114)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please keep `initLogger()` exported as we call it form main process on iOS to capture part of logs.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 55 of 55 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1493#-:-OBB0iYT24XVuyrX9K-0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @octol and @rokas-ambrazevicius)

**Pull request merged**
