### PR TITLE
Set correct file permission for recovery phrase file

### PR DESCRIPTION
**Pull request by octol**
- Add is-ready-to-connect command to nym-vpnc
- Fix: ensure mnemonic.json has restrictive file permissions
- Fix: set pending tasks up front

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @neacsu and @octol)

___
*[`nym-vpn-core/crates/nym-vpn-store/src/mnemonic/on_disk.rs` line 6 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342#-O9ii-au1y3IELTj5DAn:-O9ii-au1y3IELTj5DAo:bf3dbiy) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7ab58798a72c258505efb0bbdf27f3e7b4347a8b/nym-vpn-core/crates/nym-vpn-store/src/mnemonic/on_disk.rs#L6)):*
> ```XML
> use std::{
>     fs::{self, File},
>     os::unix::fs::PermissionsExt as _,
> ```

You probably want to guard that with `cfg(unix)` and perhaps get rid of `as _` statement as it's not necessary/clippy should be smart enough to realize that the trait is being used.

**Review by pronebird — APPROVED** [review]
FYI thanks for adding references to the workspace in cargo.toml files.

> Reviewed 6 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342#-:-O9iitJxDSEwej7ZjF1K:b-gmigtl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @neacsu and @octol)

**Review by octol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @neacsu and @pronebird)

___
*[`nym-vpn-core/crates/nym-vpn-store/src/mnemonic/on_disk.rs` line 6 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342#-O9ii-au1y3IELTj5DAn:-O9isH6HBF3dTdHO3ZTn:b-896fix) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/7ab58798a72c258505efb0bbdf27f3e7b4347a8b/nym-vpn-core/crates/nym-vpn-store/src/mnemonic/on_disk.rs#L6)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You probably want to guard that with `cfg(unix)` and perhaps get rid of `as _` statement as it's not necessary/clippy should be smart enough to realize that the trait is being used.
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1342#-:-O9j0nWUCPK4AmBpRn42:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
