### PR TITLE
APPLE: Add ability to remove helper tool

### PR DESCRIPTION
**Pull request by rokas-ambrazevicius**
Adds ability to remove daemon, if it is running.

Screenshot 2024-09-14 at 21 59 53

- - -
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1128)

### CODE REVIEW

**Comment by pronebird** [comment]
Would the app would likely remain in the broken state after removing the daemon?

**Comment by rokas-ambrazevicius** [comment]
> Would the app remain in a broken state after removing the daemon?

Nope, on connect you would start the install daemon process again. 
This is just an extra menu item just in case. Working on properly updating the whole flow of version updates for daemon.

**Review by pronebird — CHANGES_REQUESTED** [review]
I don't understand why this is needed.

**Review by pronebird — APPROVED** [review]
Let's merge this if it helps you to reinstall the daemon while developing.

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1128)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @doums and @zaneschepke)

**Pull request merged**
